crm/app/urls.py
from django.urls import path
from .views import (
    user_views,
    ad_company_views,
    client_views,
    contract_views,
    service_views,
)

app_name = "app"

urlpatterns = [
    path("", user_views.UsersIndexView.as_view(), name="user-index"),
    path("login/", user_views.UserLoginView.as_view(), name="user-login"),
    path("logout/", user_views.UserLogoutView.as_view(), name="user-logout"),
    path("services/", service_views.ServiceListView.as_view(), name="services-list"),
    path(
        "services/new/",
        service_views.ServiceCreateView.as_view(),
        name="services-create",
    ),
    path(
        "services/<int:pk>/",
        service_views.ServiceDetailView.as_view(),
        name="services-detail",
    ),
    path(
        "services/delete/<int:pk>",
        service_views.ServiceDeleteView.as_view(),
        name="services-delete",
    ),
    path(
        "services/edit/<int:pk>",
        service_views.ServiceUpdateView.as_view(),
        name="services-edit",
    ),
    path("clients/", client_views.ClientListView.as_view(), name="clients-list"),
    path(
        "clients/active",
        client_views.ActiveClientListView.as_view(),
        name="active-client-list",
    ),
    path(
        "clients/new/", client_views.ClientCreateView.as_view(), name="clients-create"
    ),
    path(
        "clients/edit/<int:pk>",
        client_views.ClientUpdateView.as_view(),
        name="clients-edit",
    ),
    path(
        "clients/detail/<int:pk>",
        client_views.ClientDetailView.as_view(),
        name="clients-detail",
    ),
    path(
        "clients/delete/<int:pk>",
        client_views.ClientDeleteView.as_view(),
        name="clients-delete",
    ),
    path(
        "contracts/", contract_views.ContractListView.as_view(), name="contracts-list"
    ),
    path(
        "contracts/new/",
        contract_views.ContractCreateView.as_view(),
        name="contracts-create",
    ),
    path(
        "contracts/detail/<int:pk>",
        contract_views.ContractDetailView.as_view(),
        name="contracts-detail",
    ),
    path(
        "contracts/edit/<int:pk>",
        contract_views.ContractUpdateView.as_view(),
        name="contracts-edit",
    ),
    path(
        "contracts/delete/<int:pk>",
        contract_views.ContractDeleteView.as_view(),
        name="contracts-delete",
    ),

    path("ads/", ad_company_views.AdCompanyListView.as_view(), name="ads-list"),
    path("ads/new/", ad_company_views.AdCompanyCreateView.as_view(), name="ads-create"),
    path("ads/detail/<int:pk>", ad_company_views.AdCompanyDetailView.as_view(), name="ads-detail"),
    path("ads/edit/<int:pk>", ad_company_views.AdCompanyUpdateView.as_view(), name="ads-edit"),
    path("ads/delete/<int:pk>", ad_company_views.AdCompanyDeleteView.as_view(), name="ads-delete"),
    path("ads/statistic/", ad_company_views.AdCompanyStatisticView.as_view(), name="ads-statistic"),
]

crm/crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("app/", include("app.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/app/templates/leads/leads-create.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Создание клиента</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Создать</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

crm/app/templates/leads/leads-delete.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Удаление лида</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <p>Вы уверены что хотите удалить "{{ object.full_name }}"?</p>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

crm/app/templates/leads/leads-detail.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Детальная информация о лиде</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <div class="card border-dark shadow" style="background: #eee">
            <div class="card-body">
                <h5 class="card-title fw-bold">{{ object.full_name }}</h5>
                <p class="card-text">{{ object.phone }}</p>
                <div class="d-flex justify-content-end fw-bold">{{ object.email }}</div>
                <div class="d-flex justify-content-center fw-bold">
                    <a href="{% url 'app:clients-edit' pk=object.pk %}" class="btn btn-primary">Редактировать</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

crm/app/templates/leads/leads-edit.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Редактирование лида</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="col"></div>
    <div class="col">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Применить</button>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

crm/app/templates/leads/leads-list.html
{% extends "_base.html" %}

{% block content %}
<h2 class="fw-bold">Клиенты</h2>
<div class="row bg-white px-3 py-3 mx-2 my-5 rounded pb-5 shadow-lg">
    <div class="hstack gap-3 pb-4">
        <a href="{% url 'app:clients-create' %}" class="btn btn-success p-2">Создать</a>
    </div>
    <div class="col">
        <ul class="list-group">
            {% for lead in leads %}
            <li class="list-group-item list-group-item-light d-flex justify-content-between">
                <a href="{% url 'app:clients-detail' pk=lead.pk %}" class="text-decoration-none link-dark">{{ lead.full_name }}</a>
                <a href="{% url 'app:clients-delete' pk=lead.pk %}" class="btn btn-danger">Удалить</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}