crm/app/urls.py
from django.urls import path
from .views import (
    user_views,
    ad_company_views,
    client_views,
    contract_views,
    service_views,
)

app_name = "app"

urlpatterns = [
    path("", user_views.UsersIndexView.as_view(), name="user-index"),
    path("login/", user_views.UserLoginView.as_view(), name="user-login"),
    path("logout/", user_views.UserLogoutView.as_view(), name="user-logout"),
    path("services/", service_views.ServiceListView.as_view(), name="services-list"),
    path(
        "services/new/",
        service_views.ServiceCreateView.as_view(),
        name="services-create",
    ),
    path(
        "services/<int:pk>/",
        service_views.ServiceDetailView.as_view(),
        name="services-detail",
    ),
    path(
        "services/delete/<int:pk>",
        service_views.ServiceDeleteView.as_view(),
        name="services-delete",
    ),
    path(
        "services/edit/<int:pk>",
        service_views.ServiceUpdateView.as_view(),
        name="services-edit",
    ),
    path("clients/", client_views.ClientListView.as_view(), name="clients-list"),
    path(
        "clients/active",
        client_views.ActiveClientListView.as_view(),
        name="active-client-list",
    ),
    path(
        "clients/new/", client_views.ClientCreateView.as_view(), name="clients-create"
    ),
    path(
        "clients/edit/<int:pk>",
        client_views.ClientUpdateView.as_view(),
        name="clients-edit",
    ),
    path(
        "clients/detail/<int:pk>",
        client_views.ClientDetailView.as_view(),
        name="clients-detail",
    ),
    path(
        "clients/delete/<int:pk>",
        client_views.ClientDeleteView.as_view(),
        name="clients-delete",
    ),
    path(
        "contracts/", contract_views.ContractListView.as_view(), name="contracts-list"
    ),
    path(
        "contracts/new/",
        contract_views.ContractCreateView.as_view(),
        name="contracts-create",
    ),
    path(
        "contracts/detail/<int:pk>",
        contract_views.ContractDetailView.as_view(),
        name="contracts-detail",
    ),
    path(
        "contracts/edit/<int:pk>",
        contract_views.ContractUpdateView.as_view(),
        name="contracts-edit",
    ),
    path(
        "contracts/delete/<int:pk>",
        contract_views.ContractDeleteView.as_view(),
        name="contracts-delete",
    ),

    path("ads/", ad_company_views.AdCompanyListView.as_view(), name="ads-list"),
    path("ads/new/", ad_company_views.AdCompanyCreateView.as_view(), name="ads-create"),
    path("ads/detail/<int:pk>", ad_company_views.AdCompanyDetailView.as_view(), name="ads-detail"),
    path("ads/edit/<int:pk>", ad_company_views.AdCompanyUpdateView.as_view(), name="ads-edit"),
    path("ads/delete/<int:pk>", ad_company_views.AdCompanyDeleteView.as_view(), name="ads-delete"),
    path("ads/statistic/", ad_company_views.AdCompanyStatisticView.as_view(), name="ads-statistic"),
]

crm/crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("app/", include("app.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/app/models.py
from django.db import models
from datetime import date
from .utils.uploads import upload_document


# Create your models here.
class Service(models.Model):
    name: str = models.CharField(max_length=200)
    description: str = models.TextField(max_length=10000, null=True)
    price: float = models.DecimalField(decimal_places=1, max_digits=20)

    class Meta:
        verbose_name = "service"

    def __str__(self):
        return self.name


class AdCompany(models.Model):
    name: str = models.CharField(max_length=200)
    service: Service = models.ForeignKey(to=Service, null=True, on_delete=models.SET_NULL)
    promotional_channel: str = models.CharField(max_length=200, null=True)
    budget: float = models.DecimalField(decimal_places=1, max_digits=20)

    @property
    def active_clients_count(self) -> int:
        return self.clients.filter(is_active=True).count()

    @property
    def inactive_clients_count(self) -> int:
        return self.clients.filter(is_active=False).count()

    @property
    def contracts_count(self) -> int:
        return self.clients.filter(contract__isnull=False).distinct().count()

    class Meta:
        verbose_name = "ad company"
        verbose_name_plural = "ad companies"

    def __str__(self) -> str:
        return self.name


class Client(models.Model):
    full_name: str = models.CharField(max_length=200)
    phone: int = models.PositiveBigIntegerField()
    email: str = models.EmailField()
    is_active: bool = models.BooleanField(default=False)
    ad_company: AdCompany = models.ForeignKey(to=AdCompany, null=True, on_delete=models.SET_NULL,
                                              related_name="clients")

    def __str__(self) -> str:
        return self.full_name

    class Meta:
        verbose_name = "client"


class Contract(models.Model):
    name: str = models.CharField(max_length=200)
    service: Service = models.ForeignKey(to=Service, on_delete=models.CASCADE)
    document: str = models.FileField(null=True, upload_to=upload_document)
    conclusion_date: date = models.DateField(null=True)
    days_of_action: int = models.PositiveIntegerField(null=True)
    price: float = models.DecimalField(decimal_places=1, max_digits=20)
    client: Client = models.ForeignKey(to=Client, on_delete=models.CASCADE, related_name="contract")

    class Meta:
        verbose_name = "contract"

    def __str__(self) -> str:
        return self.name

crm/templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>CRM</title>
</head>
<body>

<div class="main-container d-flex">
    <div class="sidebar" id="side_nav">
        <div class="header-box px-3 pt-4 pb-4">
            <h1 class="fs-4 nav-logo">
                <span class="text-black text-uppercase font-weight-bold">
                    <a class="link-dark text-decoration-none" href="{% url 'app:user-index' %}">CRM BACKOFFICE</a>
                </span>
            </h1>
        </div>
        <ul class="list-unstyled px-2">
            {% if perms.app.view_service %}
            <li><a href="{% url 'app:services-list' %}" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-microchip"></i></span><span class="ml-1"> Сервис</span>
            </a></li>
            {% endif %}
            {% if perms.app.view_adcompany %}
            <li><a href="{% url 'app:ads-list' %}" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-ad"></i></span><span class="ml-1"> Рекламные компании</span>
            </a></li>
            {% endif %}
            {% if perms.app.view_client %}
            <li><a href="{% url 'app:clients-list' %}" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-user-clock"></i></span><span class="px-1"> Клиенты</span>
            </a></li>
            {% endif %}
            {% if perms.app.view_contract %}
            <li><a href="{% url 'app:contracts-list' %}" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-file-alt"></i></span><span class="px-1"> Контракты</span>
            </a></li>
            {% endif %}
            {% if perms.app.view_client %}
            <li><a href="{% url 'app:active-client-list' %}" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-user-check"></i></span><span class="px-1"> Активные клиенты</span>
            </a></li>
            {% endif %}
            <li>
                <hr>
            </li>
            <li><a href="{% url 'app:user-logout' %}" class="bar-item text-decoration-none px-3 py-3 d-block">
                <span><i class="fas fa-sign-out-alt"></i></span><span class="px-1"> Выход</span>
            </a></li>
        </ul>
    </div>
    <div class="content px-3 pt-4">
        {% block content %}{% endblock %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>